- name: "configure {{ component }}"
  become: yes
  #hosts: "{{ component }}"
  hosts: localhost
  connection: local
  vars_files:
  - "variables-{{ env }}.yaml"
  roles: # this will automatically load a folder called roles in current working directory.
  - "{{ component }}"