- name: create instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-09863c54177764565
    sg_id: sg-01bc7ebe005fb1cb2
    ami_id: ami-09c813fb71547fc4f
    instances: ["mongodb", "catalogue","frontend"]
    status: "{{ status | default('present') }}"
  tasks:
  - name: install boto3 and botocore
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: ec2 instance creation
    amazon.aws.ec2_instance:
      state: "{{ status }}"
      name: "{{ item  }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: "{{ status }}"
      zone: daws84s.site
      record: "{{ item.item }}.daws84s.site"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address  }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"