- name: create instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-09863c54177764565
    sg_id: sg-01bc7ebe005fb1cb2
    ami_id: ami-09c813fb71547fc4f
    instances: ["mongodb", "catalogue","frontend"]
  tasks:
  - name: install boto3 and botocore
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: ec2 instance creation
    amazon.aws.ec2_instance:
      name: "{{ item  }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"